name: Docker Build And Push To Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Spring Boot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        id: buildAndPushImage
        uses: MaximilianoBz/dockerhub-buildpush@v1.0
        with:
          registry_url: 'docker.io'
          repository_name: 'routing-socal'
          user_name: 'sebmilardo'
          password: ${{ secrets.DOCKER_TOKEN }}
          image_version: 'v1.0'
          docker_file: '.'
      - name: Get pre step result output image_pull_url
        run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"
